-- MySQL
SELECT A.NAME as 'NAME', 
       B.BIRTH_DATE as 'BIRTH DAY', 
       A.ADDRESS as 'ADDRESS'
FROM EMPLOYEE_DETAILS A, 
     EMPLOYEE_BIRTHDAYS B
WHERE A.EMP_ID = B.EMP_ID
  AND A.COMPANY = 'ZOO'
ORDER BY A.NAME;